Nintendo Switch support
FWGS/hlsdk-portable pull request #353
Opened 2023-02-07 20:34 UTC by fgsfdsfgs

Adds Nintendo Switch support to both waf and cmake scripts. Complementary to FWGS/xash3d-fwgs#1238.
Building the libraries for `nswitch` requires mostly same dependencies as building the engine for it.

**Building with waf:**
```
./waf configure -T release --nswitch
./waf build
```

**Building with CMake:**
```
mkdir build && cd build
aarch64-none-elf-cmake -G"Unix Makefiles" -DCMAKE_PROJECT_HLSDK-PORTABLE_INCLUDE="$DEVKITPRO/portlibs/switch/share/SolderShim.cmake" ..
make -j
```

2023-02-07 21:01 UTC, a1batross requested changes

2023-02-07 21:01 UTC, a1batross commented on cmake/LibraryNaming.cmake
> +	set(BUILDARCH "aarch64")
Did we rename libraries, or it was a typo? Oops.

2023-02-07 21:01 UTC, a1batross commented on cmake/LibraryNaming.cmake
> +	set(BUILDARCH "aarch64")
No, it wasn't a typo!

Please, revert these. It's an engine bug, we shouldn't enforce ever change naming without a reason.

2023-02-08 00:06 UTC, fgsfdsfgs commented on cmake/LibraryNaming.cmake
> +	set(BUILDARCH "aarch64")
Reverted in b01237f.

2023-02-08 15:41 UTC, a1batross approved these changes

2023-02-08 15:42 UTC, a1batross commented
сс @nekonomicon can you take a look and merge if it's ok?

2023-02-08 17:02 UTC, nekonomicon commented
@fgsfdsfgs can you add build instructions to readme yet?

2023-02-08 18:18 UTC, a1batross commented
@nekonomicon don't you find README a bit cluttered for that? Better to decouple all the instructions into Documentation/ folder. Or have a self-documenting build tool, like Waf. :)

2023-02-08 18:39 UTC, fgsfdsfgs commented
> @fgsfdsfgs can you add build instructions to readme yet?

Done.

2023-02-08 18:44 UTC, nekonomicon commented
LGTM

2023-02-08 18:44 UTC, merged