update studio_util neon
FWGS/hlsdk-portable pull request #383
Opened 2023-08-02 16:24 UTC by MoeMod

2023-08-02 18:49 UTC, a1batross requested changes

2023-08-02 18:49 UTC, a1batross commented on cl_dll/StudioModelRenderer.cpp
> +	switch (m_pStudioHeader->numbones & 3)
I see what you're doing there but this doesn't look valid to me. 

If QuaternionSlerpX4 is just a slerping four times, you could loop through the bone group of 4, and then slerp the remaining. I wrote an example on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAJlIOAMngMmABy7gBGmMQgABykAA6oCoS2DM5uHt7xickCAUGhLBFRsZaY1ilCBEzEBGnunj6l5QKV1QR5IeGRMRZVNXUZjX3tgZ2F3dEAlBaorsTI7BwApF4AzIHIblgA1EurjgoE%2BKgAdAh72EsaAIJX14dMNsjbAG6oeOjb6KiVrlRUEG2gQI2zQrkE20mewAQnc7sDtiwmIFAW8PpC4QB2WE3bZ476/f6AgCsGNWONumIAInCbg8nq93p8CQQ/gCgRCwRCoTclti7ni8fxiICYaDZhCLnsqdtJGKuSCALTS2UY3GCvkUwXa7ZxYjA9krLwrYmfE1mrym3aW9BLYmOBhG0ji8FK2XOhXbRXbVYeiVunwuiHerhkrUa6kCwV4dmeqWrGWrNXXbWaqM63X6wSGrzGm3Wq3mu0Op1Bt2%2Bste7aBz0hsPp3aR9V4zC0JRA2P%2B3arS4J6vJ1P85s6vUG0W580F232x25v2uqs1rt1qHkht8mnD1vtmOAuM9lWhnkpiPhjOj7PjvOm4uzpcLlcw9dNylUjjTWicYm8TwcLSkVBOEcbYFFmeZMGtVYeFIAhNHfaYAGsQGJVYTgATkkLxMTQgA2DRJFWaJCOJYl9E4SQfzggDOF4BQQA0GC4OmOBYCQNAWDiOhInISh2M4%2BgomQYAFGYOIFAQVACFILAXjwBYADU8EwAB3AB5OJGE4aCaFoAhIjoiAwiosJAmqABPLTeBM5hiDM1Swm0MpYO4Xh2LYQRVIYWgLL/XgsDCVxgEcMQ20s6TMCRIxxF86S8GIJy8BeTA6JizBVDKVw9Ko4FWyo2g8DCYhzOcLAqIIfUWCYvgDGExSVPUzSXJkQQRDEdgpGa%2BQlDUKjdC4fRDBMMx9AKujIGmVA4hsAQUsVJF5nOBMFAQsyDAQiDFVU1ZeFQJLiH1LAxogaYmmmzwIAcAZPH6/xRgKIo9ASJIzqux7sjOjp7u6frToqYZXp%2B1sEpaYZPq6KIfv%2Blx6j0B4ajB8YIZOsCFgkD8v0omLAI4bZVGiHDFRwyRtmAZBnggcrwQQyZtggXBCBISCuEmXhnK0SZEIkLwTkxNZokxDQcNzaIvGiLg1jIjgKNISquA0Bjf3/bHaPoxjfOYmBEBAWYCDiTKeIgPiuOIYJWEWPGCaJkmydpymGGp3hMHwIgDr0fgWtEcQOvdrqVHUGK%2BtIZSiriSz0Y4b9SEVnbOFUzK9ZBVAqFx/HCeJ0nybt6naecDjjaZlm1fZznVlQ0vy4ryvJel6PqI4FWGLZ%2BDJa8TGlZoovm72pI7EkIA%3D%3D%3D) with the printfs to show how the loop is working.

Furhtermore, you're not using `q3` variable, and it fills q1[i] with uninitialized data in the loop after that, see lines 374-377.

2023-08-02 18:49 UTC, a1batross commented on cl_dll/studio_util.cpp
> +	float32x2_t xy_a = vget_low_f32(v1_reg);
I can't check this code without actually running it. But did you at least tested if it compiles? Because the last time it spewed errors due to invalid data types on Android and Switch.

2023-08-02 18:49 UTC, a1batross commented on cl_dll/StudioModelRenderer.cpp
> +	switch (m_pStudioHeader->numbones & 3)
Also, don't hide it under `#if 1` if you already have a generic version.

2023-08-02 18:51 UTC, a1batross commented on cl_dll/StudioModelRenderer.cpp
> +	switch (m_pStudioHeader->numbones & 3)
You might've wanted to put that #endif at the line 378, and make a new loop for position calculation.

2023-08-03 02:43 UTC, MoeMod commented on cl_dll/studio_util.cpp
> +	float32x2_t xy_a = vget_low_f32(v1_reg);
It should compile with msvc and clang. Shuffling with qword is faster so I've changed here.

2023-08-03 03:01 UTC, MoeMod commented on cl_dll/StudioModelRenderer.cpp
> +	switch (m_pStudioHeader->numbones & 3)
I removed q3, and keep the original order from q1[0] to q1[N-1].

2023-08-07 13:45 UTC, a1batross requested changes

2023-08-07 13:45 UTC, a1batross commented on cl_dll/StudioModelRenderer.cpp
> +	switch (m_pStudioHeader->numbones % 4)
What if we have only more than 4 bones but not dividable by 4?

For example, 6? With this code, only first 4 bones will be interpolated.

2023-08-07 13:46 UTC, a1batross commented
Also, the previous set of patches turned out to be glitchy on AArch64 computer running Linux, with GCC 10.

Could you check it?

2025-07-30 22:12 UTC, merged